// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9LTMiXOGyPPOUA7IlSe8zalpRvcmWxgg',
    appId: '1:1028694801286:web:bd3341d2dcd4b5fb0e4a07',
    messagingSenderId: '1028694801286',
    projectId: 'chat-app-7718b',
    authDomain: 'chat-app-7718b.firebaseapp.com',
    storageBucket: 'chat-app-7718b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl1TK5CMQiYXH4EOPVqZZjJzq4YJGMqJI',
    appId: '1:1028694801286:android:d0d6cc1bf70f5ef50e4a07',
    messagingSenderId: '1028694801286',
    projectId: 'chat-app-7718b',
    storageBucket: 'chat-app-7718b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnG0LQLuLSxl1xyvXJv3FsGKsBylrUNJs',
    appId: '1:1028694801286:ios:c2d2e97baaa3d6ea0e4a07',
    messagingSenderId: '1028694801286',
    projectId: 'chat-app-7718b',
    storageBucket: 'chat-app-7718b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
